apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCNOyip4kIclLfaUCRoT/3/2Ys7AvSoc1qy5wNjyosTIi6ZQg8UfIkRf5Bx0CbVe9u/EhNlD9QdAJFJzAVwz08ypTFvd1Hr8D6lAvOsN+zb8Mi/39sJQzF3UQd0APzn39DHN3D9ZpR+SYZfokG/nJiErCBK1vJucYQ7F978PIjNH5lmmrRKOIQEfLtfACwezF/fxFYJemKWP0R6Cyqd4GQhxJQJLx69R5+0+5LHBkzkmbl3uDFmIupm8XsdHElYJqOSAKl27Rvhpq97v3BAuANwDvKTWYmKox2SNEz95lG5RdaFl3I4TBzua3Xb/o7R7J4pKlfsULtZpfZpsoVPaY2gDDKom1ALj5uFxhlTrGwtQf9NStqJKd+GAFchsYp1hiUtLrCNIGebi7vLgIrb8fyaaCUhG0YRjkSAtek/cgFOxhuKEGy+Qbw4RBlFGMRWOl/+OSqGmRs2iEDevjjJ8sEfpYm80Iyeey5CDNPGk05oCuU34s5eFiR3y97IiU4c5B/PHarbx3i95ZYxmn2bmsFp1yaKFdrDOGH7WZPozsyKIkBllXVNMiObIO496AAXKIXk//HJJAUYYX3DwiP+K0lobhQV3B3UdX2+U63+gLsmjhqdP47dHxy71fNa0+/YniiidByvJJIieoXkFe+fRzPlJNyg6TKH6g6LlM/ekvIKj+0zbvBJ5WKuBi6mGaV1y0xCWcKhvzaYl2heFx5WtnKCK8i0b9xANT5r
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

