apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:Wxhu4Zi7PZJlfK1lzJ4/DKP4Nkg8aV3vxA==,iv:CBRLmt7Orm9EgEiGQv6INqgMhr9A1pTaIXf+W3c78h8=,tag:WiiCa1uun5uAecAkLxGSyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-01T13:58:43Z"
    mac: ENC[AES256_GCM,data:LmUxyK0q0/OG5brKvD5u5UxhacJKpOHI0yTUKbb/gj/693aOPyJOq0pJkXibl/MRpg2UjMaf+FstkkjI7qGlHgiKloEf5VKfDGEfroemvy+E8iPbB9UrqLic0yJ2qLXxInFdlHWoOHmyMewNn0tjxqp9rYvap/cdBiUyXYdGO9E=,iv:t3j6As4oHT+aJOkaQpjqi+VmUM+7q7OQyx/PReSzZ4c=,tag:a/1mf9E0F3YzV9SlO7f/Cg==,type:str]
    pgp:
        - created_at: "2025-05-01T13:58:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA+ioLI90FkGmAQv+MZdqFVnisgOZ6Vko4gdi/6gVdumHZFnnLB5LozB+9t5t
            8/iS9f7C9wnuroTDy/Wq7PWFvqFWDtZJUIK60UrTlAGvPh/e+Egdj/+b+6vYuZ26
            +kqVbjlVFDstmZmCO0TEG9ee6F7olbI4s6c7VaHvKLGQln7tO34/7ucVvpXe+H2h
            mtxnVWKzXQCW378QUSiy6jzINj4+vanxaKAyigIt0Yma0piLqe/rBTUP9IrdQ64P
            /vG1O/mr6a7evzSdpCbks+NJMIX1H+W/JczzmzqFEmTxiOfd3dv9V4SlwkKKOerd
            sqwGn1jsmboheYi/VsnM1vy0QEYDfwsIQ+B5rCg01rthmlb3moMjx7kTkLzkxqOx
            z5v0f3rZN1zIhrOdfOMHHUBeNzxOJHbtb9IwKLYV993lZT+tWy7A/JZWgnvxa6i2
            3wt3yMKUP9NjA2TLVanBjPDEAbHvOQHrx8xQiTRmOwj7mJkz9ZgId2h4eQM0UD4V
            ldlLuqtEDv3yXO5MV4TV1GYBCQIQ+6XL3fGcpmEinosZLF+agxeIzzKYlKduXbJh
            IhJA+eIuYGdB9+O3MHhKuaCMjOf5mGnjTA32xGCnno7Ddw+58RA3uqnpJzT6JALL
            NDE2GV9m+lD1piHAgxBfDbLVpOpc1io=
            =FW7p
            -----END PGP MESSAGE-----
          fp: 624FE45355F1B552963FC572F08984B16CF56737
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
